BOT_NAME = str("RPA_FINANCEIRO_01")
MAX_RETRIES = int(3)
EXECUTION_TIMEOUT = float(30.0)
IS_PRODUCTION = bool(False)

print(f'BOT NAME: {BOT_NAME} {type(BOT_NAME)}')
print(f'MAX RETRIES: {MAX_RETRIES} {type(MAX_RETRIES)}')
print(f'EXECUTION TIMEOUT: {EXECUTION_TIMEOUT} {type(EXECUTION_TIMEOUT)}')
print(f'IS PRODUCTION: {IS_PRODUCTION} {type(IS_PRODUCTION)}')
