BOT_NAME = str('RPA_FINANCEIRO AULA 01')

MAX_RETRIS = int(10)

EXECUTION_TIMEOUT = float(59.9)

IS_PRODUCTION = bool(False)

print(f'BOT NAME: {BOT_NAME} {type(BOT_NAME)}')
print(f'MAX RETRIES: {MAX_RETRIS} {type(MAX_RETRIS)}')
print(f'EXECUTION TIMEOUT: {EXECUTION_TIMEOUT} {type(EXECUTION_TIMEOUT)}')
print(f'IS PRODUCTION: {IS_PRODUCTION} {type(IS_PRODUCTION)}')